### ISSUE TITLE
FrontEnd-editing for tx_news - very nice but: Howto use?

### ISSUE THREAD

**Issue by p-Enzi** [georgringer/stdwrapvh#2]
Using typo3 7.6.3
This extension sounds very nice and usefull, but:

> You will always need the namespace declaration
> the Basic Example
> the Edit Icons

Sure namespace is needed, but where?
On top of other namespace declarations or below??
In the tx_news-templates? 
In the pages- or content-templates, partials or layout?
Or in really all templates??? 10 to 100 files to change??

Where to place the stdwrap:render definitions?
In the tx_news-templates? 
In the pages- or content-templates, partials or layout?
Or in really all templates??? 10 to 100 files to change??

Tried some tests with the news-templates.
Text inside the stdwrap:render is shown but of course not rendered.
Adding the namespace in all news-templates results completely white pages.

**Comment by georgringer** [comment]
the news template needs to adopted, correct
